s = set()
n = input("Enter a number : ")
s.add(n)
n = input("Enter a number : ")
s.add(n)
n = input("Enter a number : ")
s.add(n)
n = input("Enter a number : ")
s.add(n)
n = input("Enter a number : ")
s.add(n)
n = input("Enter a number : ")
s.add(n)
n = input("Enter a number : ")
s.add(n)
n = input("Enter a number : ")
s.add(n)
print(s)