marks = []
m1 = input("Enter the first mark: ")
marks.append(m1)
print(m1)
m2 = input("Enter the second mark: ")
marks.append(m2)
print(m2)
m3 = input("Enter the third mark: ")
marks.append(m3)
print(m3)
m4 = input("Enter the fourth mark: ")
marks.append(m4)
print(m4)
m5 = input("Enter the fifth mark: ")
marks.append(m5)
print(m5)
m6 = input("Enter the sixth mark: ")
marks.append(m6)
print(m6)
m7 = input("Enter the seventh mark: ")
marks.append(m7)
print(m7)
print(marks)  # This will print the list of marks